In [1]:
import numpy as np
import math
def MOP_Generator(n,m,J,U):
    '''
    n = # of items (x: 1 or 0)
    m = # of bags (b_k is the capacity for bag k)
    J = number of objective function
    U upperbound for c_i and a_i_k 
    '''
    
    np.random.seed(12345)

    c_total_list = []
    a_total_list = []
    b = []

    for each_J in range(J):
        c_total_list.append(np.random.randint(low=1, high=U,size = n))
    
    for each_k in range(m):
        a_total_list.append(np.random.randint(low=1, high=U,size = n))

    for each_k in range(m):
        local_sum = (math.ceil((1/2)*sum(a_total_list[each_k])))
        b.append(max(max(a_total_list[each_k]), local_sum))
    

    file = open("ins.txt","w+")
    # # of items (n)
    # file.write(str(n))
    # for each_constraint_right_hand in b:
    #     file.write(each_constraint_right_hand)

    # for cost_coef_list in range(J):
    #     file.write(c_total_list[cost_coef_list])

    # for constraint_coef_list in range(m):
    #     file.write(a_total_list[constraint_coef_list])

    # file.close()

    file.write(str(n))
    file.write("\n")
    for each_constraint_right_hand in b:
        file.write(str(each_constraint_right_hand))
        file.write("\n")

    for each_coef_list in range(J):
        
        coef_temp = ''.join(str(c_total_list[each_coef_list].tolist()).split(','))
        coef_temp = coef_temp.replace('[','')
        coef_temp = coef_temp.replace(']','')
        file.write(coef_temp)
        file.write("\n")

    for constraint_coef_list in range(m):
        constraint_coef = ''.join(str(a_total_list[constraint_coef_list].tolist()).split(','))
        constraint_coef = constraint_coef.replace('[','')
        constraint_coef = constraint_coef.replace(']','')
        file.write(constraint_coef)
        file.write("\n")
    file.close()
                
        



    return c_total_list, a_total_list, b

    



    
MOP_Generator(10,2,2,40)

([array([35, 38, 30,  2, 37, 38, 35, 30,  2, 15]),
  array([28, 17, 10, 12, 14, 11, 18, 19, 39,  8])],
 [array([24, 30, 32, 34, 28, 24, 37,  1,  4,  6]),
  array([16, 12, 15, 18,  6, 35,  9,  6, 35,  6])],
 [110, 79])

In [94]:
U = 40
n = 10
m = 2
J=2
b = []
np.random.seed(12345)

c_total_list = []
a_total_list = []

for each_J in range(J):
    c_total_list.append(np.random.randint(low=1, high=U,size = n))

for each_m in range(m):
    a_total_list.append(np.random.randint(low=1, high=U,size = n))

local_sum = (math.ceil((1/2)*sum(a_total_list[0])))

b.append(max(max(a_total_list[1]), local_sum))
print(c_total_list)

print(a_total_list)
print(local_sum)
print(b)

[array([35, 38, 30,  2, 37, 38, 35, 30,  2, 15]), array([28, 17, 10, 12, 14, 11, 18, 19, 39,  8])]
[array([24, 30, 32, 34, 28, 24, 37,  1,  4,  6]), array([16, 12, 15, 18,  6, 35,  9,  6, 35,  6])]
110
[110]


In [119]:
print(str(a_total_list[1]))
print(str(a_total_list[1].tolist()))

a = a_total_list[1].tolist()

b = ''.join(str(a).split(','))
b = b.replace('[','')
b = b.replace(']','')
print(b)

[16 12 15 18  6 35  9  6 35  6]
[16, 12, 15, 18, 6, 35, 9, 6, 35, 6]
16 12 15 18 6 35 9 6 35 6


In [121]:
n =10

file = open("ins.txt","w+")
# of items (n)
file.write(str(n))
file.write("\n")
for each_constraint_right_hand in b:
    file.write(str(each_constraint_right_hand))
    file.write("\n")

for each_coef_list in range(J):
    
    coef_temp = ''.join(str(c_total_list[each_coef_list].tolist()).split(','))
    coef_temp = coef_temp.replace('[','')
    coef_temp = coef_temp.replace(']','')
    file.write(coef_temp)
    file.write("\n")

for constraint_coef_list in range(J):
    constraint_coef = ''.join(str(c_total_list[each_coef_list].tolist()).split(','))
    constraint_coef = constraint_coef.replace('[','')
    constraint_coef = constraint_coef.replace(']','')
    file.write(constraint_coef)
    file.write("\n")
file.close()



In [6]:
np.random.randint(low = 1, high = 3, size = 10)


array([2, 2, 1, 1, 2, 1, 2, 1, 1, 1])